apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-external
  namespace: ingress-external
spec:
  destination:
    namespace: ingress-external
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.8.1
