apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx-stable
    helm:
      valueFiles:
      - nginx-values.yaml
    path: apps
    repoURL: https://helm.nginx.com/stable
    targetRevision: HEAD
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    automated: {}
