apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      valueFiles:
       - nginx.yaml
    path: apps
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.13
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    automated: {}
