apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-team1
  namespace: namespace-team1
rules:
- apiGroups:
  - '*'
  - apps
  - batch
  - extensions
  - deployments
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  verbs:
  - create
  - delete
  - describe
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind-team1
  namespace: namespace-team1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: developers-user
